#!/bin/bash
# Ninja - Fast Build System Reference
# Powered by BytesAgain — https://bytesagain.com

set -euo pipefail

cmd_intro() {
cat << 'EOF'
╔══════════════════════════════════════════════════════════════╗
║              NINJA REFERENCE                                ║
║          Ultra-Fast Build System                            ║
╚══════════════════════════════════════════════════════════════╝

Ninja is a small, focused build system designed for speed.
Unlike Make, Ninja is not meant to be written by hand — it's
generated by higher-level build systems like CMake or Meson.

NINJA vs MAKE:
  ┌──────────────┬──────────┬──────────┐
  │ Feature      │ Ninja    │ Make     │
  ├──────────────┼──────────┼──────────┤
  │ Speed        │ Fastest  │ Slow     │
  │ Parallel     │ Default  │ -j flag  │
  │ Syntax       │ Generated│ Hand-written│
  │ Deps         │ .ninja_deps│ Pattern rules│
  │ Incremental  │ Excellent│ Good     │
  │ Startup time │ ~10ms    │ ~200ms   │
  │ Portability  │ Linux/Mac/Win│ Linux/Mac │
  └──────────────┴──────────┴──────────┘

WHY NINJA IS FAST:
  1. Simple file format — no conditionals, no functions
  2. Minimal startup overhead — just parse and build
  3. Aggressive parallelism by default
  4. Compact dependency tracking (.ninja_deps binary)
  5. No-op builds in milliseconds

INSTALL:
  sudo apt install ninja-build       # Debian/Ubuntu
  brew install ninja                  # macOS
  pip install ninja                   # Python package

USAGE WITH CMAKE:
  cmake -G Ninja -B build
  ninja -C build                     # Build
  ninja -C build -j8                 # 8 parallel jobs
  ninja -C build -t targets          # List all targets
  ninja -C build -t deps             # Show dependencies
  ninja -C build -t clean            # Clean
  ninja -C build -t compdb           # Compile commands
EOF
}

cmd_syntax() {
cat << 'EOF'
BUILD.NINJA SYNTAX
====================

RULES & BUILD STATEMENTS:
  # Define a rule
  rule cc
    command = gcc -c $in -o $out -MD -MF $out.d
    depfile = $out.d
    description = CC $out

  rule link
    command = gcc $in -o $out
    description = LINK $out

  # Build statements
  build obj/main.o: cc src/main.c
  build obj/utils.o: cc src/utils.c
  build myapp: link obj/main.o obj/utils.o

VARIABLES:
  # Global variables
  cflags = -Wall -O2
  ldflags = -lm -lpthread

  rule cc
    command = gcc $cflags -c $in -o $out
    description = CC $out

  # Per-build variables
  build obj/debug.o: cc src/debug.c
    cflags = -Wall -g -O0           # Override for this build

SPECIAL VARIABLES:
  $in       Input files
  $out      Output files
  $in_newline  Inputs separated by newlines

SPECIAL RULES:
  # Phony targets (always out of date)
  build all: phony myapp tests

  # Default target
  default myapp

POOLS (limit parallelism):
  pool heavy_jobs
    depth = 2

  rule expensive
    command = heavy_compile $in $out
    pool = heavy_jobs

SUBNINJA:
  subninja lib/build.ninja           # Include another file

NINJA COMMANDS:
  ninja                              # Build default target
  ninja -j 16                        # 16 parallel jobs
  ninja -k 0                         # Keep going on error
  ninja -n                           # Dry run
  ninja -v                           # Verbose (show commands)
  ninja -t targets all               # List all targets
  ninja -t deps myapp                # Show deps of target
  ninja -t graph myapp | dot -Tpng > graph.png
  ninja -t clean                     # Clean all outputs
  ninja -t compdb cc                 # Compile database
  ninja -d stats                     # Build statistics
  ninja -w dupbuild=err              # Error on duplicate
EOF
}

cmd_generators() {
cat << 'EOF'
BUILD SYSTEM GENERATORS
=========================

CMAKE → NINJA:
  cmake -G Ninja -B build
  cmake --build build -- -j$(nproc)

  # CMakePresets.json
  {
    "configurePresets": [{
      "name": "default",
      "generator": "Ninja",
      "binaryDir": "build"
    }]
  }

MESON → NINJA:
  meson setup build                  # Generates build.ninja
  ninja -C build

GN → NINJA (Chromium):
  gn gen out/Release --args='is_debug=false'
  ninja -C out/Release chrome

CUSTOM GENERATOR (Python):
  #!/usr/bin/env python3
  import sys

  sources = ['main.c', 'utils.c', 'parser.c']
  objects = [f'obj/{s.replace(".c", ".o")}' for s in sources]

  print('rule cc')
  print('  command = gcc -c $in -o $out -MMD -MF $out.d')
  print('  depfile = $out.d')
  print()
  print('rule link')
  print('  command = gcc $in -o $out')
  print()
  for src, obj in zip(sources, objects):
      print(f'build {obj}: cc {src}')
  print()
  print(f'build myapp: link {" ".join(objects)}')
  print('default myapp')

  # python3 generate.py > build.ninja
  # ninja

NINJA LOG:
  # .ninja_log tracks build times for each edge
  # Format: start_time end_time mtime command_hash output
  # Used to detect which files need rebuilding

PERFORMANCE TIPS:
  - Use Ninja over Make for CMake projects (2-10x faster)
  - Use -j$(nproc) to max out CPU cores
  - Keep .ninja_deps and .ninja_log for incremental builds
  - Use pools for memory-heavy tasks (linking)
  - Split large build.ninja with subninja

Powered by BytesAgain — https://bytesagain.com
Contact: hello@bytesagain.com
EOF
}

show_help() {
cat << 'EOF'
Ninja - Ultra-Fast Build System Reference

Commands:
  intro        Overview, Ninja vs Make
  syntax       build.ninja format, rules, variables, pools
  generators   CMake/Meson/GN integration, custom generators

Usage: $0 <command>
EOF
}

case "${1:-help}" in
  intro)      cmd_intro ;;
  syntax)     cmd_syntax ;;
  generators) cmd_generators ;;
  help|*)     show_help ;;
esac
