#!/usr/bin/env bash
# Makefile Generator — Create language-aware Makefiles
# Usage: bash main.sh --lang <language> [--name <project>] [--output <file>]
set -euo pipefail

LANG_TARGET=""
PROJECT_NAME="myproject"
OUTPUT=""
DOCKER="false"

show_help() {
    cat << 'HELPEOF'
Makefile Generator — Create smart, well-documented Makefiles

Usage: bash main.sh --lang <language> [options]

Options:
  --lang <lang>      Language: node, python, go, java, rust, c, cpp, static
  --name <name>      Project name (default: myproject)
  --docker           Include Docker targets
  --output <file>    Output file (default: stdout)
  --help             Show this help

Powered by BytesAgain | bytesagain.com | hello@bytesagain.com
HELPEOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --lang) LANG_TARGET="$2"; shift 2;;
        --name) PROJECT_NAME="$2"; shift 2;;
        --docker) DOCKER="true"; shift;;
        --output) OUTPUT="$2"; shift 2;;
        --help|-h) show_help; exit 0;;
        *) shift;;
    esac
done

[ -z "$LANG_TARGET" ] && { echo "Error: --lang required"; show_help; exit 1; }

generate_makefile() {
    python3 << PYEOF
lang = "$LANG_TARGET"
name = "$PROJECT_NAME"
docker = "$DOCKER" == "true"

header = """# ──────────────────────────────────────
# Makefile for {name}
# Generated by BytesAgain Makefile Generator
# ──────────────────────────────────────

.DEFAULT_GOAL := help
.PHONY: help build test clean install lint fmt run dev

""".format(name=name)

help_target = """
## ── Help ──────────────────────────────
help: ## Show this help
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \\
\t\tawk 'BEGIN {FS = ":.*?## "}; {printf "\\033[36m%-20s\\033[0m %s\\n", $$1, $$2}'
"""

templates = {}

templates["node"] = header + """
NODE_BIN := node_modules/.bin

## ── Dependencies ──────────────────────
install: ## Install dependencies
\tnpm ci

## ── Development ───────────────────────
dev: ## Run development server
\tnpm run dev

run: ## Run application
\tnode index.js

## ── Build ─────────────────────────────
build: ## Build for production
\tnpm run build

## ── Test ──────────────────────────────
test: ## Run tests
\tnpm test

test-watch: ## Run tests in watch mode
\tnpm run test -- --watch

test-coverage: ## Run tests with coverage
\tnpm run test -- --coverage

## ── Code Quality ──────────────────────
lint: ## Run linter
\tnpx eslint . --ext .js,.ts

lint-fix: ## Fix lint errors
\tnpx eslint . --ext .js,.ts --fix

fmt: ## Format code
\tnpx prettier --write .

## ── Clean ─────────────────────────────
clean: ## Clean build artifacts
\trm -rf dist node_modules coverage .nyc_output
""" + help_target

templates["python"] = header + """
PYTHON := python3
VENV := .venv
PIP := $(VENV)/bin/pip

## ── Environment ───────────────────────
venv: ## Create virtual environment
\t$(PYTHON) -m venv $(VENV)
\t$(PIP) install --upgrade pip

install: venv ## Install dependencies
\t$(PIP) install -r requirements.txt

install-dev: venv ## Install dev dependencies
\t$(PIP) install -r requirements-dev.txt

## ── Development ───────────────────────
run: ## Run application
\t$(VENV)/bin/python app.py

dev: ## Run with auto-reload
\t$(VENV)/bin/python -m flask run --reload 2>/dev/null || $(VENV)/bin/uvicorn app:app --reload 2>/dev/null || $(VENV)/bin/python app.py

## ── Test ──────────────────────────────
test: ## Run tests
\t$(VENV)/bin/pytest -v

test-coverage: ## Run tests with coverage
\t$(VENV)/bin/pytest --cov=. --cov-report=html

## ── Code Quality ──────────────────────
lint: ## Run linter
\t$(VENV)/bin/flake8 .
\t$(VENV)/bin/mypy . --ignore-missing-imports

fmt: ## Format code
\t$(VENV)/bin/black .
\t$(VENV)/bin/isort .

## ── Clean ─────────────────────────────
clean: ## Clean artifacts
\trm -rf $(VENV) __pycache__ .pytest_cache .mypy_cache htmlcov *.egg-info dist build
""" + help_target

templates["go"] = header + """
BINARY := {name}
GOFLAGS := -ldflags="-w -s"

## ── Build ─────────────────────────────
build: ## Build binary
\tCGO_ENABLED=0 go build $(GOFLAGS) -o $(BINARY) .

build-all: ## Build for all platforms
\tGOOS=linux GOARCH=amd64 go build $(GOFLAGS) -o $(BINARY)-linux-amd64 .
\tGOOS=darwin GOARCH=amd64 go build $(GOFLAGS) -o $(BINARY)-darwin-amd64 .
\tGOOS=darwin GOARCH=arm64 go build $(GOFLAGS) -o $(BINARY)-darwin-arm64 .
\tGOOS=windows GOARCH=amd64 go build $(GOFLAGS) -o $(BINARY)-windows-amd64.exe .

## ── Development ───────────────────────
run: build ## Build and run
\t./$(BINARY)

dev: ## Run with air (hot reload)
\tair

## ── Test ──────────────────────────────
test: ## Run tests
\tgo test -race -v ./...

test-coverage: ## Run tests with coverage
\tgo test -race -coverprofile=coverage.out ./...
\tgo tool cover -html=coverage.out -o coverage.html

bench: ## Run benchmarks
\tgo test -bench=. -benchmem ./...

## ── Code Quality ──────────────────────
lint: ## Run linter
\tgolangci-lint run

fmt: ## Format code
\tgofmt -w .
\tgoimports -w .

vet: ## Run go vet
\tgo vet ./...

## ── Dependencies ──────────────────────
tidy: ## Tidy modules
\tgo mod tidy
\tgo mod verify

## ── Clean ─────────────────────────────
clean: ## Clean artifacts
\trm -f $(BINARY) $(BINARY)-* coverage.out coverage.html
""".format(name=name) + help_target

templates["rust"] = header + """
BINARY := target/release/{name}

## ── Build ─────────────────────────────
build: ## Build release
\tcargo build --release

build-debug: ## Build debug
\tcargo build

## ── Development ───────────────────────
run: ## Run application
\tcargo run

dev: ## Run with cargo-watch
\tcargo watch -x run

## ── Test ──────────────────────────────
test: ## Run tests
\tcargo test

test-verbose: ## Run tests verbose
\tcargo test -- --nocapture

## ── Code Quality ──────────────────────
lint: ## Run clippy
\tcargo clippy -- -D warnings

fmt: ## Format code
\tcargo fmt

fmt-check: ## Check formatting
\tcargo fmt -- --check

## ── Clean ─────────────────────────────
clean: ## Clean artifacts
\tcargo clean
""".format(name=name) + help_target

docker_section = """
## ── Docker ────────────────────────────
DOCKER_TAG := {name}:latest

docker-build: ## Build Docker image
\tdocker build -t $(DOCKER_TAG) .

docker-run: ## Run Docker container
\tdocker run --rm -p 3000:3000 $(DOCKER_TAG)

docker-push: ## Push Docker image
\tdocker push $(DOCKER_TAG)

docker-compose-up: ## Start with docker-compose
\tdocker compose up -d

docker-compose-down: ## Stop docker-compose
\tdocker compose down
""".format(name=name)

if lang not in templates:
    print("# Error: No template for language '{}'".format(lang))
    print("# Supported: {}".format(", ".join(sorted(templates.keys()))))
    import sys; sys.exit(1)

output = templates[lang]
if docker:
    output += docker_section

print(output)
print("")
print("# ---")
print("# Powered by BytesAgain | bytesagain.com | hello@bytesagain.com")
PYEOF
}

if [ -n "$OUTPUT" ]; then
    generate_makefile > "$OUTPUT"
    echo "Saved to $OUTPUT"
else
    generate_makefile
fi
